### ISSUE TITLE
No module named "paper_to_git" error after `python setup.py install`

### ISSUE THREAD

**Issue by miphilomath** [maxking/paper-to-git#10]
I am having the following error.  The steps I took:
* `$ virtualenv dropbox-sdk --python=python3`
* `$ source dropbox-sdk/bin/activate`
* `$ python setup.py install`

The error appears in the next step when I try `paper-git serve`.

![image](https://user-images.githubusercontent.com/26297035/28278075-79c069b0-6b39-11e7-802c-82ae1b9d6b3b.png)

**Comment by maxking** [comment]
This might have something to do with setuptools and the install script.

**Comment by maxking** [comment]
Turns out, setuptools changes the package names when installing them. Any `_` in the the names are replaced with `-` in the names.

I am not exactly sure how can we fix this without changing either the name of package or something else.
