### ISSUE TITLE
rename `paper_git` command to `paper-git`

### ISSUE THREAD

**Issue by maxking** [maxking/paper-to-git#2]
Change the setup.py to rename command `paper_git` to `paper-git`.

Also update the README.md to reflect the same.

**Comment by jiteshpabla** [comment]
I want to be assigned to this

**Comment by jiteshpabla** [comment]
I'm working on this.

**Comment by abstract-mib** [comment]
I am working on this.

**Comment by maxking** [comment]
@abstract-mib I am sorry I deleted your comment by mistake, looks like @jiteshpabla grabbed it before.

**Comment by maxking** [comment]
Fixed.
