### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by miphilomath** [maxking/paper-to-git#6]
```
$paper_git --help
$paper_to_git --help
```

The above two shell commands are not working.  May be you need to update the README.md file of the project and Clarify how to use this project.

![image](https://user-images.githubusercontent.com/26297035/27444374-c62c3b6c-5793-11e7-8261-2bdb16ce8d55.png)

**Comment by v123582** [comment]
I have some problem +1 ...

**Comment by maxking** [comment]
I have updated the Readme. The name of the command has changed from `paper_git` to `paper-git`. If you use the latest master branch from this repo, it should work.
